title: My personal blog - Richard Huo
email: 510344837@qq.com
description: > # this means to ignore newlines until "baseurl:"
  在这里写一些文字，和大家分享NLP方向的前沿动态。
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Richard Huo # add your name
author-pic: huo-face.jpg
about-author: Time will tell, 热爱生活的当代码农，狼人杀新手玩家。

# Contact links
email: 510344837@qq.com # Add your Email address
phone: # Add your Phone number
website: yingtaohuo.github.io # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: yingtaoHuo # Add your Github handle
twitter:  # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
# discus_identifier: ATao # Add your discus identifier
layout: default
comments: true

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
